### ISSUE TITLE
Handle browsers without localStorage space

### ISSUE THREAD

**Issue by impronunciable** [bevacqua/local-storage#1]
Some browsers that support localStorage (i.e. Safari) use a zero-quota policy for private browsing. Usually a surrounding try/catch block makes the fix.
![screen shot 2015-01-07 at 4 42 03 pm](https://cloud.githubusercontent.com/assets/165799/5652125/33edde42-968c-11e4-8b1c-6530334f47e4.png)

**Comment by bevacqua** [comment]
Snap, now returns whether saving succeeded.

**Comment by impronunciable** [comment]
<3
