### ISSUE TITLE
Does this work with subdomains?

### ISSUE THREAD

**Issue by gtwilliams03** [bevacqua/local-storage#10]
We have a public site which saves a returned authorization token to localStorage using a javascript plugin.  Then we redirect the user to an "app" subdomain (a nodejs site using your local-storage node module).  Is there a syntax for this module that, on app.mysite.com, we can access the local storage for mysite.com to retrieve the authorization token?  In basic javascript, I think it is something like 

`localStorage['mysite.com']`

(otherwise, not specifying the index would default to localStorage for app.mysite.com).

**Comment by thomassuckow** [comment]
localStorage does not support that.
You would need to do some tricks to accomplish that http://stackoverflow.com/questions/4026479/use-localstorage-across-subdomains

**Comment by gtwilliams03** [comment]
Thank you for your comment (and sorry for the late reply). We went back to using a root domain cookie for this.
