### ISSUE TITLE
I can't use any functionalities into my javascript

### ISSUE THREAD

**Issue by nanastasov** [bevacqua/local-storage#3]
Hello, so i included the module and use it like:
<code>
&lt;script src="node_modules/local-storage/dist/local-storage.js"&gt;&lt;/script&gt;
&lt;script&gt;ls.set('foo','bar'); console.log(ls.get('foo'));&lt;/script&gt;
</code>

But nothing happens instead of an error which is: <code>Uncaught ReferenceError: ls is not defined;</code>
I installed it  like that <code>npm install local-storage --save</code>
So how can i use it into my own javascript?

**Comment by bevacqua** [comment]
This currently depends on using a module loader like Browserify or AMD
