### ISSUE TITLE
Doesn't work with requirejs

### ISSUE THREAD

**Issue by mauron85** [bevacqua/local-storage#7]
Unfortunately it doesn't work with requirejs.

**Comment by jwillmer** [comment]
Wrap all files with:

``` javascript
define(function(require, exports, module) {
    // local-storage.js or tracking.js or stub.js code
});
```

and add it to your config file:

``` javascript
/// <reference path="../../require.js" />

require.config({
    baseUrl: "Scripts/",
    paths: {
        "localStorage": "libs/local-storage",
        "stub": "libs/stub",
        "tracking": "libs/tracking"
    },
    "shim": {      
        "localStorage": ["stub", "tracking"]       
    }
});
```

Have a look at the [require.js docu](http://requirejs.org/docs/api.html#config-shim).

**Comment by jwillmer** [comment]
Fixed for you? Can you close it?

**Comment by mauron85** [comment]
I don't like the idea of having 3 paths in require.config just to include one library.
Instead I have created one file, which containts functionality of local-storage.js, tracking.js and stub.js.

Anyway, thank you.

You can close this one.

**Comment by jwillmer** [comment]
I think you have to close it or the admin ;-)

FYI: I used 3 files to easily switch files with newer versions without having to merge them again.

**Comment by bevacqua** [comment]
Shouldn't the file in `dist` work out the box with require.js? It's pretty much the only reason I distribute a precompiled bundle

**Comment by jwillmer** [comment]
I think your code in `dist` is for the [AMD API](https://github.com/amdjs/amdjs-api)

**Comment by bevacqua** [comment]
Ugh
